import env from './.env';
import { AuthConfigs } from '@app/core/auth/authentication.config';

// `.env.ts` is generated by the `npm run env` command

export const environment = {
					production: true,
					version: env.npm_package_version,
					serverUrl: '/api',
					defaultLanguage: 'en-US',
					supportedLanguages: ['en-US', 'fr-FR', 'vi-VI'],
					isMockEnabled: false,
					msal: {
						clientId: 'c05cc9db-a80e-4369-8a15-9bbff1eb0666',
						authority:
							'https://login.microsoftonline.com/tfp/salehub.onmicrosoft.com/B2C_1_SignIN',
						redirectUri: 'https://prod-ops-portal.azurewebsites.net',
						postLogoutRedirectUri: 'https://prod-ops-portal.azurewebsites.net',
						validateAuthority: true,
						cacheLocation: 'localStorage',
						navigateToLoginRequestUrl: false,
						scopes:  [
						'https://saleshub.onmicrosoft.com/apiuat/read',
						'https://saleshub.onmicrosoft.com/apiuat/write'
						],
						} as AuthConfigs,
					api: {
						// COMMON
						ROOT: 'https://api.hubs.vn/',
						HOST: 'api.hubs.vn',
						// OPERATION
						OPERATION_ROOT: 'OperationPortal/',
						// MANUFACTURER
						MANUFACTURER_ROOT: 'Manufacturers/',
						// MANUFACTURER
						MANUFACTURER_PROFILES_ROOT: 'ManufacturerProfiles/',
						// MANUFACTURER
						DISTRIBUTOR_PROFILES_ROOT: 'DistributorProfiles/',
						// RETAILER PROFILES
						RETAILER_PROFILES_ROOT: 'RetailerProfiles/',
						// ORDER
						ORDERS_ROOT: 'Orders/'
					}
				};
