import env from './.env';
import { AuthConfigs } from '@app/core/auth/authentication.config';

// `.env.ts` is generated by the `npm run env` command

export const environment = {
	production: true,
	version: env.npm_package_version,
	serverUrl: '/api',
	defaultLanguage: 'en-US',
	supportedLanguages: ['en-US', 'fr-FR', 'vi-VI'],
	isMockEnabled: false,
	msal: {
		clientId: '951ab2e7-c116-4463-ba27-ec2d41c7fc71',
		authority:
			'https://login.microsoftonline.com/tfp/salehub.onmicrosoft.com/B2C_1A_operator',
		redirectUri: 'https://uat-ops.azurewebsites.net',
		postLogoutRedirectUri: 'https://uat-ops.azurewebsites.net',
		validateAuthority: true,
		navigateToLoginRequestUrl: false,
		scopes: [
			'https://saleshub.onmicrosoft.com/apiuat/read',
			'https://saleshub.onmicrosoft.com/apiuat/write'
		]
	} as AuthConfigs,
	api: {
		// COMMON
		ROOT: 'https://apiuat.hubs.vn/',
		HOST: 'apiuat.hubs.vn',
		// OPERATION
		OPERATION_ROOT: 'OperationPortal/',
		// MANUFACTURER
		MANUFACTURER_ROOT: 'Manufacturers/',
		// MANUFACTURER
		MANUFACTURER_PROFILES_ROOT: 'ManufacturerProfiles/',
		// MANUFACTURER
		DISTRIBUTOR_PROFILES_ROOT: 'DistributorProfiles/',
		// RETAILER PROFILES
		RETAILER_PROFILES_ROOT: 'RetailerProfiles/',
		// ORDER
		ORDERS_ROOT: 'Orders/'
	}
};
